[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
headless = true

[theme]
base = "light"
primaryColor = "#044A30"
backgroundColor = "#D5E9E2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0f172a"
